### ISSUE TITLE
no midi files are converted

### ISSUE THREAD

**Issue by Lernni** [Lernni/bup-to-midi-converter#1]
I use the __YAMAHA PSR E413__, which can store a maximum of 25 user tracks. After converting the backup file, exactly 25 midi files should show up. But in some cases 30+ midi files are converted.  These additional midi files are empty (they can be loaded, but only play several seconds of silence) or cannot be loaded at all.

**Comment by SlimeCraft541** [comment]
Hi! I was wondering if there's any way to solve this. I have the Yamaha YDP-141, and can transfer the .bup file but i get no midi files at all. Thanks in advance

**Comment by Lernni** [comment]
Hey! Thanks for your reply!

The converter searches for a specific keyword in the .bup file, that announces a possible midi track to extract. My first guess would be, that these keywords differ between .bup files from different instruments. So this might be the reason, why no midi files are detected.

Is it possible for you to post your .bup file, so that I can look how it differs from mine?

(I might also update the converter, so that it shows a message, when no midi tracks were found.)

**Comment by SlimeCraft541** [comment]
Hi! Yes, I here's the .bup file (Compressed in .zip)

[10YDP.zip](https://github.com/Lernni/bup-to-midi-converter/files/5142573/10YDP.zip)

**Comment by Lernni** [comment]
Mmh, just looking at the hexdump of your .bup file I couldn't find any kind of midi evidence. (It seems pretty empty, compared to mine)

I looked at the [user manual](https://usermanual.wiki/Yamaha/ydp161enomb0.1881291288/view) of your instrument and it seems like the user song stored on the device is not saved in the .bup file:

> Backup data for metronome volume and time signature, touch sensitivity, and tuning is included in the file named “10YDP.BUP”

It is stored seperately, apart from the backup in the .smf format, but is also visible with the Musicsoft Downloader:

> You can save the recorded user song to a computer. You can also load the user song data from a computer and play it back on this instrument.  The user song is saved as a Standard MIDI file (SMF). (page 28)

I haven't heard of .smf files and I don't know if you can listen to them straight away in a standard audio player, but I guess VLC player or a DAW should support them - as stated [here (VLC)](https://wiki.videolan.org/Midi/) and [here](https://www.midi.org/midi-articles/about-midi-part-4-midi-files).

Hope this helps.

**Comment by SlimeCraft541** [comment]
Ok, I guess it isn't possible. Also, I have another question, is it possible to extract the demo midi files from the piano?

**Comment by Lernni** [comment]
> Ok, I guess it isn't possible.

Are there really no other files showing up in Musicsoft Downloader? If you can transfer the .bup file, you should certainly see other files to transfer as well...

I found a [screenshot ](https://www.musiker-board.de/attachments/image1-png.78716/) of what it looked like for me, when I connected my keyboard to Musicsoft Downloader. The .bup was always in the _System Drive_ and all the other files were located in _Flash Memory_. In my case, I can only put midi files in _Flash Memory_ to play them on my keyboard. All of my user songs are stored in the .bup file.

Looking at the user manual of your instrument, I found out, that you should see the following in Musicsoft Downloader:

> Data you can transfer from this instrument to a computer
• User song : USERSONG1.MID
• Back up data : 10YDP.BUP
• Song data (once it has been loaded from the computer)

So, you should be able to see and transfer your user song.
<br>

> I have another question, is it possible to extract the demo midi files from the piano?

If the demo midi files are not considered as _Song data_, I don't think you can extract them.

**Comment by SlimeCraft541** [comment]
Ok, so, I found the user song (.MID), but there's no other files on any of the memory drives. Is there any way to access the demo midi files? Because it has over 50 songs (Listed on a book).

**Comment by Lernni** [comment]
I guess the only way to get the demo songs directly from your instrument, is to record them via analogous audio connection onto your computer. Because, as stated in the user manual, digital midi recording is only allowed for actively playing on the keyboard, not for playing back:

> Data for the demo song, 50 piano preset songs and user song cannot be transmitted via MIDI.

There might be one other way to get the demo songs, but I'm not sure if its free. (Independently of that, the service is also currently in revision.) But if you open Musicsoft Downloader, you can choose between either transfering music between your instrument and your computer, or getting songs from the [yamahamusicsoft](yamahamusicsoft.com) website, and I think this also includes getting the demo songs of your keyboard.

I never tried this, because I remembered it to cost money. But in theory, there you could download demo songs, styles and other presets for your device. It might be worth taking a look, when they finished updating it. Meanwhile, your only option is to record the songs manually as audio and if you really want the midi out of them, you could try converting the recorded audio to midi afterwards in a DAW (but I think this isn't very accurate).

**Comment by SlimeCraft541** [comment]
I went to the musicsoft website but it's not working, at least you cant log-in or register, so I think it's not possible. Thanks for the help!

**Comment by SlimeCraft541** [comment]
I read a post that said that internal memory can be accessed and connected to a computer. I will try that later

**Comment by Lernni** [comment]
Can you send a link to this post? Sounds interesting...

**Comment by SlimeCraft541** [comment]
I still don't know if it's still possible on this keyboard because the post is about Korg keyboards, but maybe it's possible. Here's the link: http://www.korgforums.com/forum/phpBB2/viewtopic.php?t=115449&sid=358b899dbc1233e9f79bcfe977fc7189 User "Vex" said that he unmounted the HDD drive and connected it to his computer.
> you could phisically unmount HDD from keyboard,and put it in a HDD rack, and connect to PC/MAC

**Comment by Lernni** [comment]
Mmh, it may be worth a try, but I believe it's not that easy to just plug out the hard drive and plug it in your computer with Yamaha instruments. I would guess, that the memory is soldered in the instrument's circuit board, so it gets very difficult to remove and to read it.

Although, it might be very interesting to see, how they implement memory in their instruments...
